name: Build and Push Frontend Image

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Build and Tag Docker Image
        run: |
          docker build -t ulasdemir472/mentorify-frontend:${{ github.sha }} -t ulasdemir472/mentorify-frontend:latest .
      
      - name: Push Docker Image
        run: |
          docker push ulasdemir472/mentorify-frontend:${{ github.sha }}
          docker push ulasdemir472/mentorify-frontend:latest

